### ISSUE TITLE
CSS: Improve the display of the links/buttons on Edit Entry

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/GravityView#2162]
The Edit Entry action links have always been quirky CSS-wise. I think we should improve them.

Before Search:
![image](https://github.com/user-attachments/assets/a84b762c-e9d8-4644-b991-4d3a53c84069)

After Search:
![image](https://github.com/user-attachments/assets/4ef7d23b-a6ab-4fc7-869c-623957a4129d)

On the Edit Entry page
![image](https://github.com/user-attachments/assets/197452f8-0d16-4e28-97f6-36a3b6b61825)

Here's a video: https://www.loom.com/share/f28e92d3e13d425986433a39b18f76b0

- [ ] Set margin on the clear button to avoid jumping after a search has been performed
```
.gv-search-clear {
    order: 2;
    display: inline-block;
    margin: 0 3%;
    height: 100%;
}
```
- [x] Set width:100% on `#publishing-action` wrapper
```css
#publishing-action{ width:100% } 
```
- [x] Remove margins from delete button:
```css
.gv-button-delete{  margin-bottom: unset;  margin-top: unset; }
```
- [x] Set same margin-botton that the update/submit button has to `.gv-button-cancel` 
```css
.gv-button-cancel{  margin-bottom: 8px; }
```

With these modifications alone we already get this look:
![image](https://github.com/user-attachments/assets/de4ddd01-0139-477e-9858-ab811aac7353)

- [ ] We also need to put a margin here but I don't know the best way since the search bar uses flexbox
![image](https://github.com/user-attachments/assets/4bfb30da-8cc9-4802-9a5f-8fadf476aa00)
